const DEVICE_INFORMATION_ID = '180a';
const CADENCE_SERVICE_ID = '1816';
const CADENCE_MEASUREMENT_ID = '2a5b';
const FITNESS_MACHINE_ID = '1826';
const INDOOR_BIKE_ID = '2ad2';
const ROWER_DEVICE_ID = '2ad1';
const DEVICE_NAME_ID = '2a00';
const APPEARANCE_ID = '2a01';
const MODEL_NUMBER_ID = '2a24';
const SERIAL_NUMBER_ID = '2a25';
const FIRMWARE_REVISION_ID = '2a26';
const HARDWARE_REVISION_ID = '2a27';
const SOFTWARE_REVISION_ID = '2a28';
const MANUFACTURER_NAME_ID = '2a29';

const BATTERY_SERVICE_ID = '180f';
const BATTERY_LEVEL_ID = '2a19';

const HEART_RATE_SERVICE_ID = '180d';
const HEART_RATE_MEASUREMENT_ID = '2a37';

const PRECOR_SERVICE_ID = 'ee07';
const PRECOR_MEASUREMENT_ID = 'e01d';
